### ISSUE TITLE
Getting an error: Failed to bind: EADDRINUSE

### ISSUE THREAD

**Issue by bweave** [shipping-docker/php-app#2]
I ran `docker-compose up -d` and got the following error. What should I look for to troubleshoot?

```
Creating network "phpapp_appnet" with driver "bridge"
Creating volume "phpapp_data" with local driver
Creating phpapp_db_1
Creating phpapp_nginx_1
Creating phpapp_redis_1
Creating phpapp_php_1

ERROR: for nginx  driver failed programming external connectivity on endpoint phpapp_nginx_1 (c3fae16f60cd9692ff4aae0ecb6f325534bfb9fd1ded3403b72083c4b795e86f): Error starting userland proxy: Failed to bind: EADDRINUSE
ERROR: Encountered errors while bringing up the project.```

Thanks!

**Comment by fideloper** [comment]
Hi! 

**The failed to bind error likely (almost definitely) means that you already have something listening on port 80 in your host machine** (your mac or Windows or Linux desktop that Docker is installed on).

## You can either:

1. Turn off whatever is using port 80 and try again, or
2. Change the `docker-compose.yml` file to use another port (something other than port `80`).

## To  change the port that Docker uses

Edit the `docker-compose.yml` file.

For example, to change from using port `80` to port `8080`, make the following change:

**From:**

```yaml
services:
  nginx:
    image: shippingdocker/nginx:latest
    ports:
     - "80:80"
    volumes:
     - ./application:/var/www/html
    networks:
     - appnet
```

**To:**

```yaml
services:
  nginx:
    image: shippingdocker/nginx:latest
    ports:
     - "8080:80"
    volumes:
     - ./application:/var/www/html
    networks:
     - appnet
```

Then you should be able to access it in your browser via `localhost:8080`.
